<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */

$viewModel = $block->getViewModel();
?>
<script>
    'use strict';

    window.onpointselect = (event) =>{
        const address = [event.address.line1, event.address.line2, event.location_description];
        Magewire.find('checkout.shipping.method.inpostlocker_standard').select(event.name, address.join("\n"), event.address_details)

        document.getElementById('inpost_locker-code').innerText = event.name;
        document.getElementById('inpost_locker-address').innerHTML = address.join('<br />');

        window.hyva.modal.pop()
    }
</script>
<script defer src='<?= $viewModel->getGeoJsUrl() ?>'></script>
<link rel="stylesheet" type="text/css" href="<?= $viewModel->getGeoCssUrl() ?>"/>
