<?php
use Hyva\Theme\ViewModel\HyvaCsp;

/** @var HyvaCsp $hyvaCsp */
?>

<script>
    const inpostStandardMethodCode = 'inpostlocker_standard';
    const inpostStandardCodMethodCode = 'inpostlocker_standardcod';
    // STANDARD
    function inpostModal() {
        return Object.assign(
            hyva.modal(),
            {
                showInpostModal() {
                    this.show('geowidget');
                },
                hideInpostModal() {
                    this.hide('geowidget');
                },
            }
        );
    }
    function inpostGeowidget() {
        return {
            openInpostModal() {
                this.$dispatch('open-geowidget');
            },
            initInpostGeowidget() {
                Alpine.store('inpost').initialized.inpostlocker_standard = true;
            }
        };
    }
    // COD
    function inpostModalCod() {
        return Object.assign(
            hyva.modal(),
            {
                showInpostModalCod() {
                    this.show('geowidget-cod');
                },
                hideInpostModalCod() {
                    this.hide('geowidget-cod');
                },
            }
        );
    }
    function inpostGeowidgetCod() {
        return {
            openInpostModalCod() {
                this.$dispatch('open-geowidget-cod');
            },
            initInpostGeowidgetCod() {
                Alpine.store('inpost').initialized.inpostlocker_standardcod = true;
            }
        };
    }
    window.addEventListener('alpine:init', () => {
        Alpine.store('inpost', {
            initialized: {
                inpostlocker_standard: false,
                inpostlocker_standardcod: false,
            }
        });
        Alpine.data('inpostModal', inpostModal);
        Alpine.data('inpostModalCod', inpostModalCod);
        Alpine.data('inpostGeowidget', inpostGeowidget);
        Alpine.data('inpostGeowidgetCod', inpostGeowidgetCod);

        // workaround Alpine.js problem with initialisation of x-data when changing method
        // https://github.com/alpinejs/alpine/pull/4509
        // https://github.com/alpinejs/alpine/discussions/4470
        // TODO: fix in future updates
        window.addEventListener('checkout:shipping:method-activate', async (event) => {
            if (event.detail.method === inpostStandardMethodCode) {
                const isInitialized = Alpine.store('inpost').initialized.inpostlocker_standard;
                if (!isInitialized) {
                    Alpine.start('inpostGeowidget');
                }
            }
            else if (event.detail.method === inpostStandardCodMethodCode) {
                const isInitialized = Alpine.store('inpost').initialized.inpostlocker_standardcod;
                if (!isInitialized) {
                    Alpine.start('inpostGeowidgetCod');
                }
            }
        })
    }, {once: true});

</script>
<?php $hyvaCsp->registerInlineScript() ?>
