<?php
use Hyva\Theme\ViewModel\HyvaCsp;

/** @var HyvaCsp $hyvaCsp */
?>

<script>
    <?php // For some reason 'checkout:init:evaluation' is too late, so we use 'checkout:init:main' instead ?>
    window.addEventListener('checkout:init:main', event => {
        hyvaCheckout.evaluation.registerValidator('validateInpostLocker', async (element, component) => {
            return new Promise((resolve, reject) => {
                let currentLocker = component.get('locker');
                if (null !== currentLocker) {
                    resolve(true);
                } else {
                    reject(false);
                }
            });
        });
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>
