<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Modal;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
// phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$viewModel = $block->getViewModel();

/** @var Hyva\Theme\ViewModel\Modal $modalViewModel */
$modalViewModel = $viewModels->require(Modal::class);
$modal = $modalViewModel
    ->createModal()
    ->withTemplate('Snowdog_HyvaCheckoutInpost::inpostlocker_standard/geowidget.phtml')
    ->withDialogRefName('geowidget')
    ->addDialogClass('relative w-full h-full pt-14 md:max-2xl md:max-h-screen-75 lg:max-w-5xl xl:max-w-7xl');
$modalBlock = $modal->getContentRenderer();
$modalBlock->setData('token', $viewModel->getGeoToken());
?>
<div
    x-data="snowdogHyvaCheckoutInpostInpostlockerStandardGeowidgetModal"
    @open-geowidget.window="showInpostModal"
>
    <?= $modal ?>
</div>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function snowdogHyvaCheckoutInpostInpostlockerStandardGeowidgetModal() {
    return Object.assign(
        inpostModal.call(this)
    )
}
window.addEventListener('alpine:init', () => Alpine.data('snowdogHyvaCheckoutInpostInpostlockerStandardGeowidgetModal', snowdogHyvaCheckoutInpostInpostlockerStandardGeowidgetModal), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>